name: Deploy to RStudio Connect

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        install.packages(c("shiny", "rsconnect"))

    - name: Deploy to RStudio Connect
      run: |
        library(rsconnect)
        rsconnect::setAccountInfo(name="${{ secrets.RSCONNECT_ACCOUNT }}", 
                                  token="${{ secrets.RSCONNECT_TOKEN }}", 
                                  secret="${{ secrets.RSCONNECT_SECRET }}")
        rsconnect::deployApp(appDir = ".")
      shell: Rscript {0}
